### ISSUE TITLE
Can't install applications -> homey offline error messages

### ISSUE THREAD

**Issue by xaviervv** [MaxvandeLaar/homey-community-store#20]
**Describe the bug**
Whenever I try to install any package, the same error popsup: App installation finished nuki.homey. Error: Homey Offline.

I am pretty sure my homey is online as I can connect to it over 4G with the homey app? Other apss like flows and insights don't seem to have any issues either.

**To Reproduce**
1. download latest release
2. unzip
3. execute exe file
4. sign in to athom account
5. 

**Expected behavior**
App to be installed to homey

**Desktop (please complete the following information):**
 - OS: Windows 10
 - App Store version: 0.2

**Comment by MaxvandeLaar** [comment]
@xaviervv So you are not connected to the same network as your Homey? Your Homey must be present in the same network as your computer when installing as the Homey Community Store is using the developer sdk to install apps.

**Comment by mruiter** [comment]
You can not install remote you have to be on the same network as you’re homey 

Verstuurd vanaf mijn iPhone

**Comment by xaviervv** [comment]
To avoid any confusion, I am connected to the same network. Even made sure I wasn't connected to my 5Ghz network as homey is using 2.4g

To clarify: "I am pretty sure my homey is online as I can connect to it over 4G with the homey app"
The reason I said this, was because the error message is telling me that Homey is offline. But I can access it through insights/flows app on my pc, and via the phone app.

**Comment by xaviervv** [comment]
Logs

```
18:11:51.698 › No apps present, start retrieving apps
index.js:66 18:11:53.147 › Has permission to show desktop notifications? granted
index.js:66 18:11:53.160 › Ask for desktop notification permission
index.js:66 18:11:53.180 › User not found, check authentication
index.js:66 18:11:53.192 › Check if user is authenticated
index.js:66 18:11:53.373 › Desktop notification answer granted
index.js:66 18:11:53.628 › User authentication check finished 
Object
index.js:66 18:11:53.643 › User profile 
Object
index.js:66 18:11:53.655 › Has permission to show desktop notifications? granted
index.js:66 18:11:53.665 › Ask for desktop notification permission
index.js:66 18:11:53.676 › User not found, check authentication
index.js:66 18:11:53.688 › Check if user is authenticated
index.js:66 18:11:53.809 › Has permission to show desktop notifications? granted
index.js:66 18:11:54.081 › Ask for desktop notification permission
index.js:66 18:11:54.091 › Active Homey 
Object
index.js:66 18:11:54.600 › Has permission to show desktop notifications? granted
index.js:66 18:11:54.700 › Ask for desktop notification permission
index.js:66 18:11:54.711 › Desktop notification answer granted
index.js:66 18:11:54.728 › Desktop notification answer granted
index.js:66 18:11:54.744 › Desktop notification answer granted
index.js:66 18:11:54.825 › User authentication check finished 
Object
index.js:66 18:11:54.840 › User profile 
Object
index.js:66 18:11:54.859 › Active Homey 
Object
index.js:66 18:11:54.873 › Has permission to show desktop notifications? granted
index.js:66 18:11:54.885 › Ask for desktop notification permission
index.js:66 18:11:54.906 › Has permission to show desktop notifications? granted
index.js:66 18:11:54.921 › Ask for desktop notification permission
index.js:66 18:11:54.935 › Desktop notification answer granted
index.js:66 18:11:54.949 › Desktop notification answer granted
index.js:66 18:12:10.180 › Finished retrieving apps 
Object
index.js:66 18:12:10.311 › Set search fields and options 
Object
index.js:66 18:12:30.502 › Progress Nuki Smart Lock 
Object
index.js:66 18:12:30.538 › Progress Nuki Smart Lock 
Object
index.js:66 18:12:30.576 › Progress Nuki Smart Lock 
Object
index.js:66 18:12:31.510 › Progress Nuki Smart Lock 
Object
index.js:66 18:12:31.546 › Progress Nuki Smart Lock 
Object
index.js:66 18:12:31.584 › Progress Nuki Smart Lock 
Object
index.js:66 18:12:31.637 › Progress Nuki Smart Lock 
Object
index.js:66 18:12:31.682 › Progress Nuki Smart Lock 
Object
index.js:66 18:12:31.725 › Progress Nuki Smart Lock 
Object
index.js:66 18:12:31.778 › Progress Nuki Smart Lock 
Object
index.js:66 18:12:31.822 › Progress Nuki Smart Lock 
Object
index.js:66 18:12:31.862 › Progress Nuki Smart Lock 
Object
index.js:66 18:12:31.900 › Progress Nuki Smart Lock 
Object
index.js:66 18:12:31.937 › Progress Nuki Smart Lock 
Object
index.js:66 18:12:31.982 › Progress Nuki Smart Lock 
Object
index.js:66 18:12:32.021 › Progress Nuki Smart Lock 
Object
index.js:66 18:12:32.056 › Progress Nuki Smart Lock 
Object
index.js:66 18:12:32.092 › Progress Nuki Smart Lock 
Object
index.js:66 18:12:32.130 › Progress Nuki Smart Lock 
Object
index.js:66 18:12:32.166 › Progress Nuki Smart Lock 
Object
index.js:66 18:12:32.210 › Progress Nuki Smart Lock 
Object
index.js:66 18:12:38.049 › App installation finished nuki.homey 
Object
error: Error: Homey Offline at t.<anonymous> (C:\Users\xavie\Downloads\Homey.Community.Store-win32-x64\Homey Community Store-win32-x64\resources\app\node_modules\athom-api\dist\index.js:1:1219729) at x (C:\Users\xavie\Downloads\Homey.Community.Store-win32-x64\Homey Community Store-win32-x64\resources\app\node_modules\athom-api\dist\index.js:1:346389) at Generator.u._invoke (C:\Users\xavie\Downloads\Homey.Community.Store-win32-x64\Homey Community Store-win32-x64\resources\app\node_modules\athom-api\dist\index.js:1:346184) at Generator.e.<computed> [as next] (C:\Users\xavie\Downloads\Homey.Community.Store-win32-x64\Homey Community Store-win32-x64\resources\app\node_modules\athom-api\dist\index.js:1:346568) at t (C:\Users\xavie\Downloads\Homey.Community.Store-win32-x64\Homey Community Store-win32-x64\resources\app\node_modules\athom-api\dist\index.js:1:9043) at C:\Users\xavie\Downloads\Homey.Community.Store-win32-x64\Homey Community Store-win32-x64\resources\app\node_modules\athom-api\dist\index.js:1:9139
stack: "Error: Homey Offline↵    at t.<anonymous> (C:\Users\xavie\Downloads\Homey.Community.Store-win32-x64\Homey Community Store-win32-x64\resources\app\node_modules\athom-api\dist\index.js:1:1219729)↵    at x (C:\Users\xavie\Downloads\Homey.Community.Store-win32-x64\Homey Community Store-win32-x64\resources\app\node_modules\athom-api\dist\index.js:1:346389)↵    at Generator.u._invoke (C:\Users\xavie\Downloads\Homey.Community.Store-win32-x64\Homey Community Store-win32-x64\resources\app\node_modules\athom-api\dist\index.js:1:346184)↵    at Generator.e.<computed> [as next] (C:\Users\xavie\Downloads\Homey.Community.Store-win32-x64\Homey Community Store-win32-x64\resources\app\node_modules\athom-api\dist\index.js:1:346568)↵    at t (C:\Users\xavie\Downloads\Homey.Community.Store-win32-x64\Homey Community Store-win32-x64\resources\app\node_modules\athom-api\dist\index.js:1:9043)↵    at C:\Users\xavie\Downloads\Homey.Community.Store-win32-x64\Homey Community Store-win32-x64\resources\app\node_modules\athom-api\dist\index.js:1:9139"
message: "Homey Offline"
__proto__: Object
app: {id: "nuki.homey", sdk: 2, brandColor: "#000000", name: {…}, tags: {…}, …}
__proto__: Object
```

message: "Start downloading Nuki Smart Lock"
message: "Completed downloading Nuki Smart Lock"
message: "Start extracting Nuki Smart Lock"
message: "Finished extracting Nuki Smart Lock"
message: "Start installation preparations Nuki Smart Lock"
message: "Finished installation preparations Nuki Smart Lock"
message: "Start installation Nuki Smart Lock"

Last line in log before finished: 
18:12:32.210 › Progress Nuki Smart Lock 
Object
step: 4
totalSteps: 4
message: "Start installation Nuki Smart Lock"
__proto__:

**Comment by MaxvandeLaar** [comment]
I know it’s been a while. Could you check [the new store](https://store.homey.community). This most likely fixed it. If not, feel free to reopen the issue
